/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 22/05/2012, 21:57:52
 */

package br.com.sca.frames;

import br.com.sca.entidades.Almoxarife;
import br.com.sca.entidades.Departamento;
import br.com.sca.entidades.Fornecedor;
import br.com.sca.entidades.Materiais;
import br.com.sca.persistencia.Dao;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public Almoxarife almoxarife;
    private Dao dao;


    public TelaPrincipal(Almoxarife almoxarife) {
        initComponents();
        dao = new Dao();
        this.almoxarife = almoxarife;
        lbBemVindo.setText("Bem-Vindo "+this.almoxarife.getFuncionario().getNomeFunc());
        System.out.println(lbBemVindo.getText());
        Date data = new Date(System.currentTimeMillis());
        lbData.setText(new SimpleDateFormat("E dd/MM/yyyy").format(data));
        if(almoxarife.getSupervisorAlmoxarife() == false){
            menuAlmoxarife.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        lbData = new javax.swing.JLabel();
        lbBemVindo = new javax.swing.JLabel();
        lbLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuFuncionario = new javax.swing.JMenuItem();
        menuAlmoxarife = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenuItem();
        menuMaterial = new javax.swing.JMenuItem();
        menuDepartamento = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRequisicao = new javax.swing.JMenuItem();
        menuCompra = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCA - Sistema de Controle de Almoxarifado");
        setResizable(false);

        lbData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbData.setForeground(new java.awt.Color(204, 204, 204));
        lbData.setText("jLabel1");
        lbData.setBounds(1160, 10, 120, 21);
        jLayeredPane2.add(lbData, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbBemVindo.setFont(new java.awt.Font("Arial", 0, 24));
        lbBemVindo.setForeground(new java.awt.Color(204, 204, 204));
        lbBemVindo.setText("jLabel1");
        lbBemVindo.setBounds(20, 10, 850, 29);
        jLayeredPane2.add(lbBemVindo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(0, 0, 1290, 110);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sca/imagem/logo.jpg"))); // NOI18N
        lbLogo.setText("jLabel1");
        lbLogo.setBounds(0, 0, 1290, 670);
        jLayeredPane1.add(lbLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Cadastro");

        menuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuFuncionario.setText("Funcionário");
        menuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuFuncionario);

        menuAlmoxarife.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuAlmoxarife.setText("Almoxarife");
        menuAlmoxarife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlmoxarifeActionPerformed(evt);
            }
        });
        jMenu1.add(menuAlmoxarife);

        menuCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCategoria.setText("Categoria");
        menuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(menuCategoria);

        menuMaterial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuMaterial.setText("Material");
        menuMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaterialActionPerformed(evt);
            }
        });
        jMenu1.add(menuMaterial);

        menuDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuDepartamento.setText("Departamento");
        menuDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuDepartamento);

        menuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        menuFornecedor.setText("Fornecedor");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuFornecedor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentação");

        menuRequisicao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        menuRequisicao.setText("Requisição");
        menuRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRequisicaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuRequisicao);

        menuCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        menuCompra.setText("Compra");
        menuCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompraActionPerformed(evt);
            }
        });
        jMenu2.add(menuCompra);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        menuRelatorio.setText("Relatórios");
        menuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioActionPerformed(evt);
            }
        });
        jMenu3.add(menuRelatorio);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlmoxarifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlmoxarifeActionPerformed
       TelaAlmoxarife telaAlmoxarife = new TelaAlmoxarife(almoxarife);
       telaAlmoxarife.setVisible(true);
    }//GEN-LAST:event_menuAlmoxarifeActionPerformed

    private void menuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuncionarioActionPerformed
        if(dao.pesquisar("Departamento.findAll").isEmpty()){
            JOptionPane.showMessageDialog(null, "Não há nenhum departamento cadastrado.");
        }
 else{

        TelaFuncionario telaFuncionario = new TelaFuncionario();
        telaFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_menuFuncionarioActionPerformed

    private void menuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaActionPerformed
        TelaCategoria telaCategoria = new TelaCategoria();
        telaCategoria.setVisible(true);
    }//GEN-LAST:event_menuCategoriaActionPerformed

    private void menuRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRequisicaoActionPerformed
        TelaRequisicao requisicao = new TelaRequisicao(this);
        requisicao.setVisible(true);
    }//GEN-LAST:event_menuRequisicaoActionPerformed

    private void menuCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompraActionPerformed
        TelaCompra telaCompra = new TelaCompra(this);
        telaCompra.setVisible(true);
    }//GEN-LAST:event_menuCompraActionPerformed

    private void menuDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepartamentoActionPerformed
        TelaDepartamento departamento = new TelaDepartamento();
        departamento.setVisible(true);
    }//GEN-LAST:event_menuDepartamentoActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
        TelaFornecedorTelefone fornecedor = new TelaFornecedorTelefone();
        fornecedor.setVisible(true);
    }//GEN-LAST:event_menuFornecedorActionPerformed

    private void menuMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaterialActionPerformed
        if(dao.pesquisar("Categoria.findAll").isEmpty()){
            JOptionPane.showMessageDialog(null, "Não há nenhuma categoria cadastrada.");
        }
 else{
        TelaMateriais material = new TelaMateriais();
        material.setVisible(true);
        }
    }//GEN-LAST:event_menuMaterialActionPerformed

    private void menuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioActionPerformed
        TelaRelatorioRequisicoes relatorio = new TelaRelatorioRequisicoes();
        relatorio.setVisible(true);
    }//GEN-LAST:event_menuRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbBemVindo;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JMenuItem menuAlmoxarife;
    private javax.swing.JMenuItem menuCategoria;
    private javax.swing.JMenuItem menuCompra;
    private javax.swing.JMenuItem menuDepartamento;
    private javax.swing.JMenuItem menuFornecedor;
    private javax.swing.JMenuItem menuFuncionario;
    private javax.swing.JMenuItem menuMaterial;
    private javax.swing.JMenuItem menuRelatorio;
    private javax.swing.JMenuItem menuRequisicao;
    // End of variables declaration//GEN-END:variables

}
