/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaItemCompra.java
 *
 * Created on 30/04/2012, 21:08:38
 */
package br.com.sca.frames;

import br.com.sca.controller.CompraController;
import br.com.sca.entidades.MaterialCompra;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Anderson
 */
public class TelaItemCompra extends javax.swing.JFrame {

    TelaCompra telaCompra;
    MaterialCompra material;
    boolean finalizar;

    public TelaItemCompra(TelaCompra telaCompra, MaterialCompra material, boolean finalizar) {
        initComponents();
        this.telaCompra = telaCompra;
        telaCompra.setEnabled(false);
        this.finalizar = finalizar;
        this.material = material;
        lbItem.setText(material.getMateriais().getNomeMat());
        spinnerQuant.setModel(new SpinnerNumberModel(1, 1, 999999, 1));
    }

    public TelaItemCompra() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbPreco = new javax.swing.JLabel();
        lbQuant = new javax.swing.JLabel();
        lbItem = new javax.swing.JLabel();
        fTfPreco = new javax.swing.JFormattedTextField();
        btConfirmar = new javax.swing.JButton();
        spinnerQuant = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 80, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lbPreco.setText("Preço:");

        lbQuant.setText("Quantidade:");

        lbItem.setText("NomeItemCompra");

        fTfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        fTfPreco.setNextFocusableComponent(spinnerQuant);

        btConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sca/imagem/apply32x32.png"))); // NOI18N
        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setText("Item:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbQuant)
                    .addComponent(lbPreco)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fTfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbItem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addComponent(btConfirmar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(fTfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuant)
                    .addComponent(spinnerQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btConfirmar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        boolean entradasCorretas = true;
        if (fTfPreco.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o preço do item.");
        } else {
            if (fTfPreco.getText().length() > 10) {
                material.setPrecoMatcom(BigDecimal.ZERO);
                fTfPreco.setText("");
                entradasCorretas = false;
                JOptionPane.showMessageDialog(null, "Valor muito alto para o preço!");
            } else {
                material.setPrecoMatcom(new BigDecimal(Double.parseDouble(fTfPreco.getText().replace(".", "").replace(",", "."))).setScale(2, RoundingMode.HALF_UP));
            }
            material.setQuantMatcom(new BigInteger(new String().valueOf(spinnerQuant.getValue())));
            if (entradasCorretas) {
                if (this.finalizar) {
                    CompraController controller = new CompraController();
                    controller.alterarItemCompra(material);
                    telaCompra.atualizarItemCompra();
                    this.dispose();
                    telaCompra.setEnabled(true);
                } else {
                    telaCompra.adicionarItemCompra(material);
                    telaCompra.setEnabled(true);
                    this.dispose();
                    telaCompra.setEnabled(true);
                }
            }
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        telaCompra.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaItemCompra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JFormattedTextField fTfPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbItem;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQuant;
    private javax.swing.JSpinner spinnerQuant;
    // End of variables declaration//GEN-END:variables
}
